// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHSiCHlzBBzynjd8_s1VsGlUnV3kfO9B8',
    appId: '1:914435781453:web:29983120feeb7c3c837d04',
    messagingSenderId: '914435781453',
    projectId: 'chatapptute-f8f94',
    authDomain: 'chatapptute-f8f94.firebaseapp.com',
    storageBucket: 'chatapptute-f8f94.appspot.com',
    measurementId: 'G-YYZN6P125X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5IMGDYQR0SfEyFcFkdhPy66uzYyU9Bxg',
    appId: '1:914435781453:android:117db0af04235172837d04',
    messagingSenderId: '914435781453',
    projectId: 'chatapptute-f8f94',
    storageBucket: 'chatapptute-f8f94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkRYudCh7cFOC8PMHlU8xGqhgjxiIFeG4',
    appId: '1:914435781453:ios:603974f1ba9a9e1e837d04',
    messagingSenderId: '914435781453',
    projectId: 'chatapptute-f8f94',
    storageBucket: 'chatapptute-f8f94.appspot.com',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkRYudCh7cFOC8PMHlU8xGqhgjxiIFeG4',
    appId: '1:914435781453:ios:e9676426211a25af837d04',
    messagingSenderId: '914435781453',
    projectId: 'chatapptute-f8f94',
    storageBucket: 'chatapptute-f8f94.appspot.com',
    iosBundleId: 'com.example.weather.RunnerTests',
  );
}
